config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post '/sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  put '/account', to: 'users#update'
  get '/account', to: 'users#edit'
  delete '/account', to: 'users#destroy'
  resources :active_sessions, only: [:destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :users, only: [:show]
  resources :games, only: %i[show index]
  resources :user_games, only: %i[show create update destroy] do
    resources :countries
  end
  get  "/admin", to: "admin#index"

  patch  "/admin/users/:id",     to: "admin#update_user",   as: :admin_update_user
  delete "/admin/users/:id",     to: "admin#destroy_user",  as: :admin_destroy_user
  patch  "/admin/countries/:id", to: "admin#update_country",  as: :admin_update_country
  delete "/admin/countries/:id", to: "admin#destroy_country", as: :admin_destroy_country
  resources :country, only: %i[update edit]
  get '/user_games/:id/recruit', to: 'user_games/recruit#index'
  get '/user_games/:id/build', to: 'user_games/build#index'
  get '/user_games/:id/explore', to: 'user_games/explore#index'
  get '/user_games/:id/research', to: 'user_games/research#index'
  get '/user_games/:id/countries', to: 'user_games/countries#index'
  get '/user_games/:id/countries/:id', to: 'user_games/countries#show'
  get '/user_games/:id/reports', to: 'user_games/battle_reports#index'
  get '/user_games/:id/country_battle_reports/:id', to: 'user_games/battle_reports#show'
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home
    @user = current_user
    @user_game = UserGame.find_by(user_id: @user.id) if @user
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<center>
  <div id="banner">
    <h1>Tactical Warfare</h1>
  </div>
  <br>

  <div class="green-bg">
    <div class="tan-bg">
      <h2>Glory Awaits!</h2>

      <div class="tutorial-button">
        <%= link_to "Watch The Tutorial!", "https://youtu.be/Hm6zDKreTvg", class: "tutorial-link", target: "_blank" %>
      </div>

      <% if @user.present? %>
        <br>

        <% if @user_game.present? %>
          <%= button_to "Continue", user_game_path(@user_game), method: :get, class: "big-button" %>
        <% else %>
          <%= button_to "Start Game", games_path, method: :get, class: "big-button" %>
        <% end %>

        <br>

        <% if @user.admin? %>
          <%= button_to "Admin Panel", admin_path, method: :get, class: "big-button" %>
          <br>
        <% end %>

        <%= button_to "Sign Out", "/logout", method: :delete, class: "big-button" %>

      <% else %>
        <%= button_to "Sign Up!", "/sign_up", method: :get, class: "big-button" %>
        -OR-
        <%= button_to "Sign In!", "/login", method: :get, class: "big-button" %>
        <br>
      <% end %>

      <details>
        <summary><h3><b>Future Updates</b></h3></summary>
        Messaging Feature
        <br>Alliances
        <br>Game Rounds
        <br>Resource System
        <br>MANY more units with unique bonuses
        <br>Messages with Notifications
        <br>Recruit/Build by number rather than turns used
        <br>Attack Range by Score
        <br>Espionage
        <br>Missiles
        <br>Government Types with Bonuses
        <br>Public Opinion with Nationwide Effects
        <br>Naval Invasions
      </details>

      <details>
        <summary><h3><b>Update Logs</b></h3></summary>
        <br><b>16/08/2023</b> Add helicopter units...
        <br><b>13/08/2023</b> Add individual naval and air attacks...
        <br><b>10/08/2023</b> Update appearance...
        <br><b>06/08/2023</b> Tweak lab upkeep...
        <br><b>05/08/2023</b> Add unit decomission...
        <br><b>04/08/2023</b> Fix battle report casualties...
        <br><b>03/08/2023</b> Add basic research...
        <br><b>29/07/2023</b> Adjust infrastructure upkeep...
        <br><b>26/07/2023</b> Add battle loot...
      </details>

    </div>
  </div>
</center>