config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post '/sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  put '/account', to: 'users#update'
  get '/account', to: 'users#edit'
  delete '/account', to: 'users#destroy'
  resources :active_sessions, only: [:destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :users, only: [:show]
  resources :games, only: %i[show index]
  resources :user_games, only: %i[show create update destroy] do
    resources :countries
  end
  get  "/admin", to: "admin#index"

  patch  "/admin/users/:id",     to: "admin#update_user",   as: :admin_update_user
  delete "/admin/users/:id",     to: "admin#destroy_user",  as: :admin_destroy_user
  patch  "/admin/countries/:id", to: "admin#update_country",  as: :admin_update_country
  delete "/admin/countries/:id", to: "admin#destroy_country", as: :admin_destroy_country
  resources :country, only: %i[update edit]
  get '/user_games/:id/recruit', to: 'user_games/recruit#index'
  get '/user_games/:id/build', to: 'user_games/build#index'
  get '/user_games/:id/explore', to: 'user_games/explore#index'
  get '/user_games/:id/research', to: 'user_games/research#index'
  get '/user_games/:id/countries', to: 'user_games/countries#index'
  get '/user_games/:id/countries/:id', to: 'user_games/countries#show'
  get '/user_games/:id/reports', to: 'user_games/battle_reports#index'
  get '/user_games/:id/country_battle_reports/:id', to: 'user_games/battle_reports#show'
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
  validate :unique_combination, on: :create

  def unique_combination
    return unless UserGame.exists?(game_id: game_id.to_s, user_id: user_id.to_s)

    errors.add(:base,
               'User game already exists.')
  end
end

app/controllers/user_games/battle_reports_controller.rb
class UserGames::BattleReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_game = UserGame.find_by_user_id(current_user.id)
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @attack_reports = CountryBattleReport.where(attacker_country_id: @country.id).order('created_at DESC')
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
    return unless params[:read] == '1'

    @unread_reports.mark_as_read! :all, for: @country
    redirect_to "/user_games/#{@user_game.id}/reports"
  end

  def show
    @user_game = UserGame.find_by_user_id(current_user.id)
    @report = CountryBattleReport.find(params[:id])
    @user = current_user
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
    @attacker = Country.find(@report.attacker_country_id)
    @defender = Country.find(@report.defender_country_id)
    return unless params[:read] == '1'

    @report.mark_as_read! for: @defender
  end
end

app/controllers/user_games/build_controller.rb
class UserGames::BuildController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_game = UserGame.find_by_user_id(current_user.id)
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
  end
end

app/controllers/user_games/countries_controller.rb
class UserGames::CountriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_game = UserGame.find_by_user_id(current_user.id)
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @countries = Country.all
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
  end

  def show
    @user_game = UserGame.find_by_user_id(current_user.id)
    @country = Country.find(params[:id])
    @user = current_user
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
  end
end

app/controllers/user_games/explore_controller.rb
class UserGames::ExploreController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_game = UserGame.find_by_user_id(current_user.id)
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
  end
end

app/controllers/user_games/recruit_controller.rb
class UserGames::RecruitController < ApplicationController
  before_action :authenticate_user!

  def index
    @basic_infantry = BasicInfantry.new(1)
    @air_infantry = AirInfantry.new(1)
    @sea_infantry = SeaInfantry.new(1)
    @armor_infantry = ArmorInfantry.new(1)
    @basic_armored = BasicArmored.new(1)
    @air_armored = AirArmored.new(1)
    @sea_armored = SeaArmored.new(1)
    @armor_armored = ArmorArmored.new(1)
    @basic_aircraft = BasicAircraft.new(1)
    @air_aircraft = AirAircraft.new(1)
    @sea_aircraft = SeaAircraft.new(1)
    @armor_aircraft = ArmorAircraft.new(1)
    @basic_ship = BasicShip.new(1)
    @air_ship = AirShip.new(1)
    @sea_ship = SeaShip.new(1)
    @armor_ship = ArmorShip.new(1)
    @attack_helicopter = AttackHelicopter.new(1)
    @transport_helicopter = TransportHelicopter.new(1)
    @naval_helicopter = NavalHelicopter.new(1)
    @user_game = UserGame.find_by_user_id(current_user.id)
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
  end
end

app/controllers/user_games/research_controller.rb
class UserGames::ResearchController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_game = UserGame.find_by_user_id(current_user.id)
    @game = Game.find(@user_game.game_id)
    @country = Country.where(user_id: current_user.id, game_id: @user_game.game_id).first
    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order('created_at DESC')
    @unread_reports = @defense_reports.unread_by(@country)
  end
end

app/controllers/user_games_controller.rb
class UserGamesController < ApplicationController
  before_action :authenticate_user!

  def create
    @game = Game.find(params[:game_id])

    @user_game = UserGame.find_or_initialize_by(user_id: current_user.id, game_id: @game.id)

    if @user_game.persisted?
      redirect_to user_game_path(@user_game), notice: "Account Already Exists!"
      return
    end

    ActiveRecord::Base.transaction do
      @user_game.save!

      @country = @game.countries.new(name: params[:country_name], user_id: current_user.id)
      @country.save!
    end

    redirect_to user_game_path(@user_game), notice: "Welcome to Game: #{@game.id}"
  rescue ActiveRecord::RecordInvalid => e
    flash.now[:alert] = "Error: #{e.record.errors.full_messages.to_sentence}"
    render :new, status: :unprocessable_entity
  end

  def destroy
    @user_game = UserGame.find(params[:user_game_id])
    @country = Country.find_by(user_id: current_user.id, game_id: @user_game.game_id)
    @country.destroy
    @user_game.destroy
    redirect_to user_path(current_user)
  end

  def show
    @user_game = UserGame.find(params[:id])

    # Prevent other users from viewing someone else's user_game
    unless @user_game.user_id == current_user.id
      redirect_to root_path, alert: "Not authorized"
      return
    end

    @game = Game.find(@user_game.game_id)
    @country = Country.find_by(user_id: current_user.id, game_id: @user_game.game_id)

    if @country.nil?
      # If you want to auto-clean bad data:
      @user_game.destroy
      redirect_to games_path, alert: "Your country name is taken try another!"
      return
    end

    @defense_reports = CountryBattleReport.where(defender_country_id: @country.id).order(created_at: :desc)
    @unread_reports = @defense_reports.unread_by(@country)
  end

  def update
    @user_game = UserGame.find_by_user_id(current_user.id)
    @game = Game.find(@user_game.game_id)
    @country = Country.find_by(user_id: current_user.id, game_id: @user_game.game_id)

    explore_land if params[:explore_land].present?
    perform_attack if attack_params_present?
    build_or_demolish if build_or_demolish_params_present?
    recruit_units if recruit_units_params_present?
    decommission_units if decommission_params_present?
  end

  private

  def explore_land
    redirect_with_alert('Not Enough Turns') and return unless @country.turns >= params[:explore_land].to_i

    @country.explore_land(params[:explore_land])
    redirect_to user_game_path(@user_game)
  end

  def perform_attack
    @attacker = Country.find(params[:attacker_id])
    redirect_with_alert('Not Enough Turns') and return unless sufficient_turns_for_attack(params[:air_attack],
                                                                                          params[:naval_attack], params[:ground_attack], @attacker.turns) == true

    @defender = Country.find(params[:defender_id])
    @battle_report = CountryBattleReport.create!(attacker_country_id: @attacker.id, defender_country_id: @defender.id,
                                                 game_id: @game.id)
    conduct_battle(@attacker, @defender, @battle_report, params[:ground_attack], params[:air_attack],
                   params[:naval_attack])
    @battle_report.select_victor
    redirect_to "/user_games/#{@user_game.id}/country_battle_reports/#{@battle_report.id}"
  end

  def build_or_demolish
    build_keys = %i[infrastructure shops barracks armories hangars dockyards labs houses]
    demo_keys  = %i[
      demolish_infrastructure demolish_shops demolish_barracks demolish_armories
      demolish_hangars demolish_dockyards demolish_labs demolish_houses
    ]

    if demo_keys.any? { |k| params[k].to_i > 0 }
      total_turns_needed = (demo_keys.sum { |k| params[k].to_i } / 10.0).ceil
      redirect_with_alert('Not Enough Turns') and return unless @country.turns >= total_turns_needed

      @country.demolish(
        params[:demolish_infrastructure].to_i,
        params[:demolish_shops].to_i,
        params[:demolish_barracks].to_i,
        params[:demolish_armories].to_i,
        params[:demolish_hangars].to_i,
        params[:demolish_dockyards].to_i,
        params[:demolish_labs].to_i,
        params[:demolish_houses].to_i
      )

      redirect_to user_game_path(@user_game)
      return
    end

    total_turns_needed = build_keys.sum { |k| params[k].to_i }
    redirect_with_alert('Not Enough Turns') and return unless @country.turns >= total_turns_needed
    redirect_with_alert('Not Enough Land') and return unless @country.land_check(*build_keys.map { |k| params[k].to_i })

    @country.build(*build_keys.map { |k| params[k].to_i })
    redirect_to user_game_path(@user_game)
  end

  def recruit_units
    unit_params = %i[infantry air_infantry sea_infantry armor_infantry armored air_armored sea_armored
                     armor_armored ships air_ships sea_ships armor_ships aircraft air_aircraft sea_aircraft armor_aircraft]

    total_turns_needed = unit_params.sum { |param| params[param].to_i }
    redirect_with_alert('Not Enough Turns') and return unless @country.turns >= total_turns_needed
    redirect_with_alert('Not Enough Money') and return unless @country.has_enough_money?(params)
    unless @country.has_enough_pop_and_capacity?(params)
      redirect_with_alert('Not Enough Population or Capacity Reached') and return
    end

    @country.recruit_units(params)
    redirect_to user_game_path(@user_game)
  end

  def decommission_units
    @country.decomission(params)
    redirect_to user_game_path(@user_game)
  end

  def redirect_with_alert(message)
    redirect_to user_game_path(@user_game), alert: message
  end

  def attack_params_present?
    params[:ground_attack].present? || params[:air_attack].present? || params[:naval_attack].present?
  end

  def build_or_demolish_params_present?
    params[:infrastructure].present? || params[:shops].present? || params[:barracks].present? || params[:armories].present? || params[:hangars].present? || params[:dockyards].present? || params[:labs].present? || params[:houses].present? || params[:demolish_infrastructure].present? || params[:demolish_shops].present? || params[:demolish_barracks].present? || params[:demolish_armories].present? || params[:demolish_hangars].present? || params[:demolish_dockyards].present? || params[:demolish_labs].present? || params[:demolish_houses].present?
  end

  def recruit_units_params_present?
    params[:infantry].present? || params[:air_infantry].present? || params[:sea_infantry].present? || params[:armor_infantry].present? || params[:armored].present? || params[:air_armored].present? || params[:sea_armored].present? || params[:armor_armored].present? || params[:aircraft].present? || params[:air_aircraft].present? || params[:sea_aircraft].present? || params[:armor_aircraft].present? || params[:ship].present? || params[:air_ship].present? || params[:sea_ship].present? || params[:armor_ship].present? || params[:attack_helicopter].present? || params[:transport_helicopter].present? || params[:naval_helicopter].present? 
  end

  def decommission_params_present?
    params[:basic_infantry_decomission].present? || params[:air_infantry_decomission].present? || params[:sea_infantry_decomission].present? || params[:armor_infantry_decomission].present? || params[:basic_armored_decomission].present? || params[:air_armored_decomission].present? || params[:sea_armored_decomission].present? || params[:armor_armored_decomission].present? || params[:basic_aircraft_decomission].present? || params[:air_aircraft_decomission].present? || params[:sea_aircraft_decomission].present? || params[:armor_aircraft_decomission].present? || params[:basic_ship_decomission].present? || params[:air_ship_decomission].present? || params[:sea_ship_decomission].present? || params[:armor_ship_decomission].present? || params[:attack_helicopter_decomission].present? || params[:transport_helicopter_decomission].present? || params[:naval_helicopter_decomission].present?
  end

  def sufficient_turns_for_attack(air, sea, ground, turns)
    if air.present? || sea.present? 
      if turns >= 50
        @attacker.take_turns(50)
        true
      else
        false
      end
    elsif ground.present?
      if turns >= 150
        @attacker.take_turns(150)
        true
      else
        false
      end
    end
  end

  def conduct_battle(attacker, defender, battle_report, ground, air, sea)
    if air.present? || ground.present?
      attacker.air_to_air_attack(attacker, defender, battle_report)
      defender.air_to_air_attack(defender, attacker, battle_report, 1)
    end
    if sea.present? || ground.present?
      attacker.navy_to_navy_attack(attacker, defender, battle_report)
      defender.air_to_navy_attack(defender, attacker, battle_report, 1)
      defender.navy_to_navy_attack(defender, attacker, battle_report, 1)
    end
    if ground.present?
      defender.air_to_armor_attack(defender, attacker, battle_report, 1)
      defender.navy_to_armor_attack(defender, attacker, battle_report, 1)
      attacker.ground_to_ground_attack(attacker, defender, battle_report)
    end
    battle_report.select_victor
  end
end

app/views/user_games/battle_reports/index.html.erb
<center><div id="banner">
<h1>Tactical Warfare</h1>
</div>
<h4><div id="banner-2">
<table class='full-table'>
  <tr>
    <td>
      <%= link_to 'Main&nbsp;Menu'.html_safe, root_path, method: :get, class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Dashboard', user_game_path(@user_game), class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Recruit', "/user_games/#{@user_game.id}/recruit", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Explore&nbsp;Land'.html_safe,"/user_games/#{@user_game.id}/explore", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Build', "/user_games/#{@user_game.id}/build", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Research', "/user_games/#{@user_game.id}/research", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Nation&nbsp;Leaderboard'.html_safe, "/user_games/#{@user_game.id}/countries", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to "Reports&nbsp;(#{@unread_reports.length})".html_safe, "/user_games/#{@user_game.id}/reports", class: 'banner-links' %>
    </td>
  </tr>
</table>
</div>
</h4>
</center>

<center>
<div class="green-bg">
<h3>Reports</h3>
  <div class="tan-bg">
<% if @unread_reports != [] %>
  <h3>Unread Reports:</h3>
  <%= link_to "Mark all as read", "/user_games/#{@user_game.id}/reports?read=1",  data: { turbo_method: :get, turbo_confirm: "Are you sure?" }%>
  <div class='reports'>
  <% @unread_reports.each do |report|%>
  <br><%= link_to "Battle # #{report.id}, Attacker: #{Country.find(report.attacker_country_id).name}, Defender: #{Country.find(report.defender_country_id).name}", "/user_games/#{@user_game.id}/country_battle_reports/#{report.id}?read=1", class: "banner-links"%><br>
  <% end %>
  </div>
<% end %>

<h4>Attack Reports:</h4><br> 
<div class='reports'>
<% @attack_reports.each do |report|%>
<br><%= link_to "Battle # #{report.id}, Attacker: #{Country.find(report.attacker_country_id).name}, Defender: #{Country.find(report.defender_country_id).name}", "/user_games/#{@user_game.id}/country_battle_reports/#{report.id}", class: "banner-links"%><br>
<% end %>
</div>

<h4>Defense Reports:</h4><br> 
<div class='reports'>
<% @defense_reports.each do |report|%>
<br><%= link_to "Battle # #{report.id}, Attacker: #{Country.find(report.attacker_country_id).name}, Defender: #{Country.find(report.defender_country_id).name}", "/user_games/#{@user_game.id}/country_battle_reports/#{report.id}", class: "banner-links"%><br>
<% end %>
</div>
</div>
</center>
</div>

app/views/user_games/battle_reports/show.html.erb
<center><div id="banner">
<h1>Tactical Warfare</h1>
</div>
<h4><div id="banner-2">
<table class='full-table'>
  <tr>
    <td>
      <%= link_to 'Main&nbsp;Menu'.html_safe, root_path, method: :get, class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Dashboard', user_game_path(@user_game), class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Recruit', "/user_games/#{@user_game.id}/recruit", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Explore&nbsp;Land'.html_safe,"/user_games/#{@user_game.id}/explore", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Build', "/user_games/#{@user_game.id}/build", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Research', "/user_games/#{@user_game.id}/research", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to 'Nation&nbsp;Leaderboard'.html_safe, "/user_games/#{@user_game.id}/countries", class: 'banner-links' %>
    </td>
    <td>
      <%= link_to "Reports&nbsp;(#{@unread_reports.length})".html_safe, "/user_games/#{@user_game.id}/reports", class: 'banner-links' %>
    </td>
  </tr>
</table>
</div>
</h4>

<div class="green-bg">
  <h3><%=@attacker.name%> vs <%=@defender.name%>, <%=@report.created_date%></h3>
<div class="tan-bg">
<h4>
<% if @report.attacker? %>
  Attacker has won!
<% elsif @report.defender? %>
  Defender has won!
<% else %>
  Bettle was a draw!
<%end%>
<h4>


<h4>Attacker:</h4>
<%= link_to "#{@attacker.name}", user_game_country_path(@user_game, @attacker), method: :get %><br>
Money Looted: <%= number_to_human(@report.taken_money) %><br> 
Attacker Infantry Casualties: <%= number_to_human(@report.defender_killed_basic_infantry + @report.defender_killed_sea_infantry + @report.defender_killed_air_infantry + @report.defender_killed_armor_infantry) %><br> 
Attacker Armored Casualties: <%= number_to_human(@report.defender_killed_basic_armored + @report.defender_killed_sea_armored + @report.defender_killed_air_armored + @report.defender_killed_armor_armored) %><br>
Attacker Ship Casualties: <%= number_to_human(@report.defender_killed_basic_ship + @report.defender_killed_sea_ship + @report.defender_killed_air_ship + @report.defender_killed_armor_ship) %><br>
Attacker Aircraft Casualties: <%= number_to_human(@report.defender_killed_basic_aircraft + @report.defender_killed_sea_aircraft + @report.defender_killed_air_aircraft + @report.defender_killed_armor_aircraft) %><br>

<h4>Defender:</h4>
<%= link_to "#{@defender.name}", user_game_country_path(@user_game, @defender), method: :get %><br>
Defender Infantry Casualties: <%= number_to_human(@report.killed_basic_infantry + @report.killed_sea_infantry + @report.killed_air_infantry + @report.killed_armor_infantry) %> <br>
Defender Armored Casualties: <%= number_to_human(@report.killed_basic_armored + @report.killed_sea_armored + @report.killed_air_armored + @report.killed_armor_armored) %> <br>
Defender Ship Casualties: <%= number_to_human(@report.killed_basic_ship + @report.killed_sea_ship + @report.killed_air_ship + @report.killed_armor_ship) %> <br>
Defender Aircraft Casualties: <%= number_to_human(@report.killed_basic_aircraft + @report.killed_sea_aircraft + @report.killed_air_aircraft + @report.killed_armor_aircraft) %> <br>
Land Taken: <%= number_to_human(@report.taken_land) %><br>
Houses Taken: <%= number_to_human(@report.taken_houses) %><br>
infrastructure Destroyed: <%= number_to_human(@report.destroyed_infrastructure) %><br>
Shops Taken: <%= number_to_human(@report.taken_shops) %><br>
Labs Taken: <%= number_to_human(@report.taken_labs) %><br>
Barracks Taken: <%= number_to_human(@report.taken_barracks) %><br>
Armories Taken: <%= number_to_human(@report.taken_armory) %><br>
Hangars Taken: <%= number_to_human(@report.taken_hangars) %><br>
Dockyards Taken: <%= number_to_human(@report.taken_dockyards) %><br>
Houses Destroyed: <%= number_to_human(@report.destroyed_houses) %><br>
Shops Destroyed: <%= number_to_human(@report.destroyed_shops) %><br>
Labs Destroyed: <%= number_to_human(@report.destroyed_labs) %><br>
Barracks Destroyed: <%= number_to_human(@report.destroyed_barracks) %><br>
Armories Destroyed: <%= number_to_human(@report.destroyed_armory) %><br>
Hangars Destroyed: <%= number_to_human(@report.destroyed_hangars) %><br>
Dockyards Destroyed: <%= number_to_human(@report.destroyed_dockyards) %><br>
</div>
</center>
</div>