config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'
  post '/sign_up', to: 'users#create'
  get 'sign_up', to: 'users#new'
  resources :confirmations, only: %i[create edit new], param: :confirmation_token
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  resources :passwords, only: %i[create edit new update], param: :password_reset_token
  put '/account', to: 'users#update'
  get '/account', to: 'users#edit'
  delete '/account', to: 'users#destroy'
  resources :active_sessions, only: [:destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :users, only: [:show]
  resources :games, only: %i[show index]
  resources :user_games, only: %i[show create update destroy] do
    resources :countries
  end
  get  "/admin", to: "admin#index"

  patch  "/admin/users/:id",     to: "admin#update_user",   as: :admin_update_user
  delete "/admin/users/:id",     to: "admin#destroy_user",  as: :admin_destroy_user
  patch  "/admin/countries/:id", to: "admin#update_country",  as: :admin_update_country
  delete "/admin/countries/:id", to: "admin#destroy_country", as: :admin_destroy_country
  resources :country, only: %i[update edit]
  get '/user_games/:id/recruit', to: 'user_games/recruit#index'
  get '/user_games/:id/build', to: 'user_games/build#index'
  get '/user_games/:id/explore', to: 'user_games/explore#index'
  get '/user_games/:id/research', to: 'user_games/research#index'
  get '/user_games/:id/countries', to: 'user_games/countries#index'
  get '/user_games/:id/countries/:id', to: 'user_games/countries#show'
  get '/user_games/:id/reports', to: 'user_games/battle_reports#index'
  get '/user_games/:id/country_battle_reports/:id', to: 'user_games/battle_reports#show'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  has_many :active_sessions, dependent: :destroy
  has_many :user_games

  enum :role, { default: 0, admin: 1 }
  attr_accessor :current_password

  has_secure_password

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  validates :unconfirmed_email, format: { with: URI::MailTo::EMAIL_REGEXP, allow_blank: true }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true
  validates :password_digest, presence: true
  validates :password, confirmation: { case_sensitive: true }
  validates :username, presence: true, uniqueness: { case_sensitive: true }

  MAILER_FROM_EMAIL = 'no-reply@example.com'
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, _value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, 'One or more password arguments are required' if passwords.empty?
    raise ArgumentError, 'One or more finder arguments are required' if identifiers.empty?

    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  def confirm!
    if unconfirmed_or_reconfirming?
      return false if unconfirmed_email.present? && !update(email: unconfirmed_email, unconfirmed_email: nil)

      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def confirmed?
    confirmed_at.present?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def unconfirmed?
    !confirmed?
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  private

  def downcase_email
    return if email.nil?

    self.email = email.downcase
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?

    self.unconfirmed_email = unconfirmed_email.downcase
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[edit destroy update show]
  #before_action :redirect_if_authenticated, only: [:create]

  def create
    @user = User.find_by_username(params[:user][:username])
    if @user && @user.unconfirmed?
      #@user.send_confirmation_email!
      login @user
      redirect_to user_path(@user), alert: 'Please confirm your email.'
    elsif @user && @user.confirmed?
      login @user
      redirect_to user_path(@user)
    else
      @user = User.new(create_user_params)
      if @user.save
        #@user.send_confirmation_email!
        login @user
        redirect_to user_path(@user), notice: 'Please check your email for confirmation instructions.'
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def new
    if user_signed_in?
      @user = current_user
      redirect_to user_path(@user)
      flash[:alert] = 'Already Signed In'
      return
    end
    @user = User.new
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, notice: 'Your account has been deleted.'
  end

  def edit
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    if @user.authenticate(params[:user][:current_password])
      if @user.update(update_user_params)
        if params[:user][:unconfirmed_email].present?
          @user.send_confirmation_email!
          redirect_to root_path, notice: 'Check your email for confirmation instructions.'
        else
          redirect_to root_path, notice: 'Account updated.'
        end
      else
        render :edit, status: :unprocessable_entity
      end
    else
      flash.now[:error] = 'Incorrect password'
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @user = current_user
    @user_games = @user.user_games

    redirect_to admin_path if @user.admin?
  end

  private

  def create_user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:current_password, :password, :username, :password_confirmation, :unconfirmed_email)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<center>
<div id="banner">
<h1>Tactical Warfare</h1>
</div>
<div class="tan-bg">
<%= form_with model: @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div>
    <%= form.label :email, "Current Email" %>
    <%= form.email_field :email, disabled: true %>
  </div>
  <div>
    <%= form.label :unconfirmed_email, "New Email" %>
    <%= form.text_field :unconfirmed_email %>
  </div>
  <div>
    <%= form.label :password, "Password (leave blank if you don't want to change it)" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
  <hr/>
  <div>
    <%= form.label :current_password, "Current password (we need your current password to confirm your changes)" %>
    <%= form.password_field :current_password, required: true %>
  </div>
  <%= form.submit "Update Account", class: 'button' %>
<% end %>

<h2>Current Logins</h2>
<% if @active_sessions.any? %>
  <%= button_to "Log out of all other sessions", destroy_all_active_sessions_path, method: :delete %>
  <table>
    <thead>
      <tr>
        <th>User Agent</th>
        <th>IP Address</th>
        <th>Signed In At</th>
        <th>Sign Out</th>
      </tr>
    </thead>
    <tbody>
      <%= render @active_sessions %>
    </tbody>
  </table>
<% end %>
</div>

app/views/users/new.html.erb
<center>
<div id="banner">
<h1>Tactical Warfare</h1>
</div>
<div class="tan-bg">
<%= form_with model: @user, url: sign_up_path do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>
  <%= form.submit "Sign Up", class: 'button' %>
<% end %>
</div>
</center>

app/views/users/show.html.erb
<center>
  <div id="banner">
    <h1>Tactical Warfare</h1>
  </div>
  <br>

  <div class="green-bg">
    <h3>User Profile</h3>

    <div class="tan-bg">
      <h3>Active Games:</h3>

      <p>
        <% @user_games.each do |ug| %>
          <%= link_to "Game: #{ug.game_id}", user_game_path(ug) %><br>

          <%= button_to "Delete Game: #{ug.id}",
                user_game_path(ug),
                method: :delete,
                form: { data: { turbo_confirm: "Are you sure?" } },
                class: "button" %>

          <br><br>
        <% end %>
      </p>

      <%= link_to "Join a Game", games_path %><br><br>
      <%= button_to "Sign Out", "/logout", method: :delete, class: "button" %>
    </div>
  </div>
</center>